spring:
  jpa:
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  h2:
    console:
      enable: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE